### ISSUE TITLE
Allow to disable dynamic zooming in navigation

### ISSUE THREAD

**Issue by linker-c** [penguian/tesla-issues-discussion#26]
Please allow us to disable the dynamic zooming feature.  It changes the map perspective which is really annoying.  Most folks just want to manually zoom to the level and stays at that level.
A slight bend in map would cause the navigation to zoom all the way in for no reason.  There's a hack to place a random pin on the map to disable dynamic zooming.  Might as well just allow us to disable it.

**Comment by penguian** [comment]
This is a wishlist item rather than a bug report. It may be better for you to fork this repository so that you can use it for your own purposes. Otherwise, you are welcome to use https://teslaideas.ideascale.com/

Also, it would help if you could specify the exact software version where you see the undesired behaviour, so that changes can be tracked.
